services:
  db:
    image: postgres:15.4
    ports:
      - $POSTGRES_PORT:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=$POSTGRES_DATABASE
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 2s
      timeout: 5s
      retries: 2

  pgweb:
    image: sosedoff/pgweb:0.14.1
    ports:
      - 8081:8081
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      - PGWEB_DATABASE_URL=postgres://$POSTGRES_USER:$POSTGRES_PASSWORD@db:$POSTGRES_PORT/$POSTGRES_DATABASE?sslmode=disable
