name: "Formatting"

on: push

jobs:
  black:
    name: black (23.7.0)
    runs-on: ubuntu-latest
    steps:
      - name: Install dependencies
        run: pip install taskipy==1.12.0 black==23.7.0

      - name: Checkout
        uses: actions/checkout@v3
        with:
          sparse-checkout: .

      - name: x
        run: ls -al && pip list

      - name: Run black
        run: task formatting_black_check
