name: Formatting

on: 
  push:

jobs:
  black:
    name: black (23.7.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install taskipy==1.12.0 black==23.7.0

      - name: Run black
        run: task formatting_black_check
