name: Tests

on:
  workflow_run:
    workflows: [Python linters]
    types: [completed]
    branches: ["**"]

jobs:
  pytest:
    name: pytest (7.4.0)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: '3.11' 

      - name: Install dependencies
        run: pip install poetry && poetry install

      - name: Run tests
        run: poetry run task test

      - name: Coverage report
        run: poetry run task test_report
